// src/data/TransactionData.js

const TRANSACTION_DATA = [
    {
      id: 1,
      transactionNo: "TX001",
      passengerName: "John Doe",
      driverName: "Alex Smith",
      totalCost: 120.5,
      coinsInWallet: 50,
      status: "Completed",
    },
    {
      id: 2,
      transactionNo: "TX002",
      passengerName: "Jane Smith",
      driverName: "David Johnson",
      totalCost: 80,
      coinsInWallet: 30,
      status: "Pending",
    },
    {
      id: 3,
      transactionNo: "TX003",
      passengerName: "Chris Evans",
      driverName: "Tom Clark",
      totalCost: 100,
      coinsInWallet: 40,
      status: "Cancelled",
    },
    {
      id: 4,
      transactionNo: "TX004",
      passengerName: "Emily Davis",
      driverName: "Michael Brown",
      totalCost: 150.75,
      coinsInWallet: 60,
      status: "Completed",
    },
    {
      id: 5,
      transactionNo: "TX005",
      passengerName: "Robert Wilson",
      driverName: "Sarah Lee",
      totalCost: 95.25,
      coinsInWallet: 35,
      status: "Pending",
    },
    {
      id: 6,
      transactionNo: "TX006",
      passengerName: "Linda Martinez",
      driverName: "James Taylor",
      totalCost: 200,
      coinsInWallet: 80,
      status: "Completed",
    },
    {
      id: 7,
      transactionNo: "TX007",
      passengerName: "David Anderson",
      driverName: "Patricia Thomas",
      totalCost: 60,
      coinsInWallet: 25,
      status: "Failed",
    },
    {
      id: 8,
      transactionNo: "TX008",
      passengerName: "Barbara Jackson",
      driverName: "Charles Harris",
      totalCost: 175.5,
      coinsInWallet: 55,
      status: "Completed",
    },
    {
      id: 9,
      transactionNo: "TX009",
      passengerName: "James White",
      driverName: "Jennifer Martin",
      totalCost: 85,
      coinsInWallet: 20,
      status: "Pending",
    },
    {
      id: 10,
      transactionNo: "TX010",
      passengerName: "Susan Thompson",
      driverName: "William Garcia",
      totalCost: 130,
      coinsInWallet: 45,
      status: "Cancelled",
    },
    {
      id: 11,
      transactionNo: "TX011",
      passengerName: "Charles Martinez",
      driverName: "Elizabeth Robinson",
      totalCost: 210.75,
      coinsInWallet: 70,
      status: "Completed",
    },
    {
      id: 12,
      transactionNo: "TX012",
      passengerName: "Karen Clark",
      driverName: "Thomas Rodriguez",
      totalCost: 55.5,
      coinsInWallet: 15,
      status: "Failed",
    },
    {
      id: 13,
      transactionNo: "TX013",
      passengerName: "Nancy Lewis",
      driverName: "Christopher Lewis",
      totalCost: 190,
      coinsInWallet: 65,
      status: "Completed",
    },
  ];
  
  export default TRANSACTION_DATA;
  